services:
  restapi:
    container_name: connect.restapi
    build:
      context: .
      dockerfile: RestAPI/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - locationservice
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - GrpcSettings:LocationServiceUrl=http://connect.locationservice:6000
    networks:
      - connectwork
    image: tpham2580/connect-dotnet-restapi

  locationservice:
    container_name: connect.locationservice
    build:
      context: .
      dockerfile: LocationService/Dockerfile
    ports:
      - "6000:6000"
    depends_on:
      - redis
    environment:
      - ASPNETCORE_URLS=http://+:6000
      - ConnectionStrings__Redis=redis:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - connectwork
    image: tpham2580/connect-dotnet-locationservice

  redis:
    container_name: connect.redis
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - connectwork
    command: ["redis-server", "--save", "60", "1", "--dir", "/data", "--requirepass", "${REDIS_PASSWORD}"]  # Save every 60s or 1 key change

  redis-seeder:
    build: 
      context: ./redis
    depends_on:
      - redis
    environment: 
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - connectwork
    entrypoint: ["/bin/sh", "/seed-redis.sh"]

  businessservice:
    container_name: connect.businessservice
    build:
      context: .
      dockerfile: BusinessService/Dockerfile
    ports:
      - "6001:6001"
    environment:
      - ASPNETCORE_URLS=http://+:6001
    networks:
      - connectwork
    image: tpham2580/connect-dotnet-businessservice

networks:
  connectwork:
    driver: bridge

volumes:
  redis-data: 
