services:
  restapi:
    build:
      context: .
      dockerfile: RestAPI/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - locationservice
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - GrpcSettings:LocationServiceUrl=http://locationservice:6000
    networks:
      - connectwork
    image: tpham2580/connect-dotnet-restapi

  locationservice:
    build:
      context: .
      dockerfile: LocationService/Dockerfile
    ports:
      - "6000:6000"
    depends_on:
      - redis
    environment:
      - ASPNETCORE_URLS=http://+:6000
      - ConnectionStrings__Redis=redis:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - connectwork
    image: tpham2580/connect-dotnet-locationservice

  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - connectwork
    command: ["redis-server", "--save", "60", "1", "--dir", "/data", "--requirepass", "${REDIS_PASSWORD}"]  # Save every 60s or 1 key change

  redis-seeder:
    build: 
      context: ./redis
    depends_on:
      - redis
    environment: 
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - connectwork
    entrypoint: ["/bin/sh", "/seed-redis.sh"]

  businessservice:
    build:
      context: .
      dockerfile: BusinessService/Dockerfile
    ports:
      - "6001:6001"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_URLS=http://+:6001
      - ConnectionStrings__Postgres=Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    networks:
      - connectwork
    image: tpham2580/connect-dotnet-businessservice
  
  postgres:
    build:
      context: ./postgres
    restart: always
    ports:
      - "5432:5432"
    volumes: 
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - connectwork

networks:
  connectwork:
    driver: bridge

volumes:
  redis-data: 
  postgres-data:
