services:
  restapi:
    build:
      context: .
      dockerfile: RestAPI/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - locationservice
    environment:
      - ASPNETCORE_URLS=http://+:5000
    image: tpham2580/connect-dotnet-restapi

  locationservice:
    build:
      context: .
      dockerfile: LocationService/Dockerfile
    ports:
      - "6000:6000"
    depends_on:
      - redis
    environment:
      - ASPNETCORE_URLS=http://+:6000
      - ConnectionStrings__Redis=redis:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    image: tpham2580/connect-dotnet-locationservice

  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--save", "60", "1", "--dir", "/data", "--requirepass", "${REDIS_PASSWORD}"]  # Save every 60s or 1 key change

  redis-seeder:
    build: 
      context: ./redis
    depends_on:
      - redis
    environment: 
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    entrypoint: ["/bin/sh", "/seed-redis.sh"]

volumes:
  redis-data: 
