FROM mcr.microsoft.com/dotnet/sdk:8.0 as dev

WORKDIR /app
COPY . .

RUN dotnet tool install --global dotnet-watch
ENV PATH="$PATH:/root/.dotnet/tools"

CMD [ "dotnet", "watch", "run", "--urls", "http://0.0.0.0:5000" ]
