FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 5000

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY RestAPI/RestAPI.csproj RestAPI/
RUN dotnet restore RestAPI/RestAPI.csproj

COPY RestAPI/ RestAPI/
WORKDIR /src/RestAPI
RUN dotnet build -c Release -o /app/build
RUN dotnet publish -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "RestAPI.dll"]
