services:
  restapi:
    build:
      context: .
      dockerfile: RestAPI/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - grpcservice
    environment:
      - ASPNETCORE_URLS=http://+:5000
    image: tpham2580/connect-dotnet-restapi

  grpcservice:
    build:
      context: .
      dockerfile: GrpcService/Dockerfile
    ports:
      - "6000:6000"
    depends_on:
      - redis
    environment:
      - ASPNETCORE_URLS=http://+:6000
    image: tpham2580/connect-dotnet-grpcservice

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
